const mongoose = require("mongoose"),
Schema = mongoose.Schema,
config = require("../config.js");

module.exports = mongoose.model("Guild", new Schema({

    /* REQUIRED */
    id: { type: String },
    
    /* MEMBERSDATA */
    membersData: { type: Object, default: {} },
    members: [{ type: Schema.Types.ObjectId, ref: "Member" }],
    channellogs: { type: String, default: '' },

    /* CONFIGURATION */
    language: { type: String, default: config.defaultLanguage },
    prefix: { type: String, default: config.prefix },
    color: { type: String, default: config.embed.color },
    plugins: { type: Object, default: {
        hentai: {
            enabled: true
        },
        autorole: {
            enabled: false,
            role: null
        },
        logs: false
    }},
    level: { type: Boolean, default: true },
    autohentai: { type: Boolean, default: false },
    autohentaichannel: { type: String, default: '' },
    autohentaitime: { type: Number, default: 0 },
    hentaimsg: { type: Number, default: 0 },
    ticketsopen: { type: Number, default: 0 },
    ticketsenable: { type: Number, default: 0 },


    
    ticketenable0: { type: Boolean, default: false },
    ticketopen0: { type: Number, default: 0 },
    ticketchannel0: { type: String, default: '' },
    ticketmessage0: { type: String, default: '' },
    ticketreact0: { type: String, default: '671334152418623489' },
    ticketcategoryon0: { type: Boolean, default: false },
    ticketcategory0: { type: String, default: '' },
    ticketchannelname0: { type: String, default: 'Тикет' },
    ticketchannelperms0: { type: String, default: '' },
    ticketmessage1enable0: { type: Boolean, default: true },
    ticketmessage1send0: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable0: { type: Boolean, default: true },
    ticketmessage2send0: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable0: { type: Boolean, default: true },
    ticketmessage3send0: { type: String, default: 'embed' },
    ticketcloseonlyadmin0: { type: Boolean, default: true },
    ticketclosemsg0: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg0: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable1: { type: Boolean, default: false },
    ticketopen1: { type: Number, default: 0 },
    ticketchannel1: { type: String, default: '' },
    ticketmessage1: { type: String, default: '' },
    ticketreact1: { type: String, default: '671334152418623489' },
    ticketcategoryon1: { type: Boolean, default: false },
    ticketcategory1: { type: String, default: '' },
    ticketchannelname1: { type: String, default: 'Тикет' },
    ticketchannelperms1: { type: String, default: '' },
    ticketmessage1enable1: { type: Boolean, default: true },
    ticketmessage1send1: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable1: { type: Boolean, default: true },
    ticketmessage2send1: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable1: { type: Boolean, default: true },
    ticketmessage3send1: { type: String, default: 'embed' },
    ticketcloseonlyadmin1: { type: Boolean, default: true },
    ticketclosemsg1: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg1: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable2: { type: Boolean, default: false },
    ticketopen2: { type: Number, default: 0 },
    ticketchannel2: { type: String, default: '' },
    ticketmessage2: { type: String, default: '' },
    ticketreact2: { type: String, default: '671334152418623489' },
    ticketcategoryon2: { type: Boolean, default: false },
    ticketcategory2: { type: String, default: '' },
    ticketchannelname2: { type: String, default: 'Тикет' },
    ticketchannelperms2: { type: String, default: '' },
    ticketmessage1enable2: { type: Boolean, default: true },
    ticketmessage1send2: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable2: { type: Boolean, default: true },
    ticketmessage2send2: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable2: { type: Boolean, default: true },
    ticketmessage3send2: { type: String, default: 'embed' },
    ticketcloseonlyadmin2: { type: Boolean, default: true },
    ticketclosemsg2: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg2: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable3: { type: Boolean, default: false },
    ticketopen3: { type: Number, default: 0 },
    ticketchannel3: { type: String, default: '' },
    ticketmessage3: { type: String, default: '' },
    ticketreact3: { type: String, default: '671334152418623489' },
    ticketcategoryon3: { type: Boolean, default: false },
    ticketcategory3: { type: String, default: '' },
    ticketchannelname3: { type: String, default: 'Тикет' },
    ticketchannelperms3: { type: String, default: '' },
    ticketmessage1enable3: { type: Boolean, default: true },
    ticketmessage1send3: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable3: { type: Boolean, default: true },
    ticketmessage2send3: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable3: { type: Boolean, default: true },
    ticketmessage3send3: { type: String, default: 'embed' },
    ticketcloseonlyadmin3: { type: Boolean, default: true },
    ticketclosemsg3: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg3: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable4: { type: Boolean, default: false },
    ticketopen4: { type: Number, default: 0 },
    ticketchannel4: { type: String, default: '' },
    ticketmessage4: { type: String, default: '' },
    ticketreact4: { type: String, default: '671334152418623489' },
    ticketcategoryon4: { type: Boolean, default: false },
    ticketcategory4: { type: String, default: '' },
    ticketchannelname4: { type: String, default: 'Тикет' },
    ticketchannelperms4: { type: String, default: '' },
    ticketmessage1enable4: { type: Boolean, default: true },
    ticketmessage1send4: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable4: { type: Boolean, default: true },
    ticketmessage2send4: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable4: { type: Boolean, default: true },
    ticketmessage3send4: { type: String, default: 'embed' },
    ticketcloseonlyadmin4: { type: Boolean, default: true },
    ticketclosemsg4: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg4: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable5: { type: Boolean, default: false },
    ticketopen5: { type: Number, default: 0 },
    ticketchannel5: { type: String, default: '' },
    ticketmessage5: { type: String, default: '' },
    ticketreact5: { type: String, default: '671334152418623489' },
    ticketcategoryon5: { type: Boolean, default: false },
    ticketcategory5: { type: String, default: '' },
    ticketchannelname5: { type: String, default: 'Тикет' },
    ticketchannelperms5: { type: String, default: '' },
    ticketmessage1enable5: { type: Boolean, default: true },
    ticketmessage1send5: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable5: { type: Boolean, default: true },
    ticketmessage2send5: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable5: { type: Boolean, default: true },
    ticketmessage3send5: { type: String, default: 'embed' },
    ticketcloseonlyadmin5: { type: Boolean, default: true },
    ticketclosemsg5: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg5: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable6: { type: Boolean, default: false },
    ticketopen6: { type: Number, default: 0 },
    ticketchannel6: { type: String, default: '' },
    ticketmessage6: { type: String, default: '' },
    ticketreact6: { type: String, default: '671334152418623489' },
    ticketcategoryon6: { type: Boolean, default: false },
    ticketcategory6: { type: String, default: '' },
    ticketchannelname6: { type: String, default: 'Тикет' },
    ticketchannelperms6: { type: String, default: '' },
    ticketmessage1enable6: { type: Boolean, default: true },
    ticketmessage1send6: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable6: { type: Boolean, default: true },
    ticketmessage2send6: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable6: { type: Boolean, default: true },
    ticketmessage3send6: { type: String, default: 'embed' },
    ticketcloseonlyadmin6: { type: Boolean, default: true },
    ticketclosemsg6: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg6: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable7: { type: Boolean, default: false },
    ticketopen7: { type: Number, default: 0 },
    ticketchannel7: { type: String, default: '' },
    ticketmessage7: { type: String, default: '' },
    ticketreact7: { type: String, default: '671334152418623489' },
    ticketcategoryon7: { type: Boolean, default: false },
    ticketcategory7: { type: String, default: '' },
    ticketchannelname7: { type: String, default: 'Тикет' },
    ticketchannelperms7: { type: String, default: '' },
    ticketmessage1enable7: { type: Boolean, default: true },
    ticketmessage1send7: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable7: { type: Boolean, default: true },
    ticketmessage2send7: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable7: { type: Boolean, default: true },
    ticketmessage3send7: { type: String, default: 'embed' },
    ticketcloseonlyadmin7: { type: Boolean, default: true },
    ticketclosemsg7: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg7: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable8: { type: Boolean, default: false },
    ticketopen8: { type: Number, default: 0 },
    ticketchannel8: { type: String, default: '' },
    ticketmessage8: { type: String, default: '' },
    ticketreact8: { type: String, default: '671334152418623489' },
    ticketcategoryon8: { type: Boolean, default: false },
    ticketcategory8: { type: String, default: '' },
    ticketchannelname8: { type: String, default: 'Тикет' },
    ticketchannelperms8: { type: String, default: '' },
    ticketmessage1enable8: { type: Boolean, default: true },
    ticketmessage1send8: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable8: { type: Boolean, default: true },
    ticketmessage2send8: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable8: { type: Boolean, default: true },
    ticketmessage3send8: { type: String, default: 'embed' },
    ticketcloseonlyadmin8: { type: Boolean, default: true },
    ticketclosemsg8: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg8: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },
    
    ticketenable9: { type: Boolean, default: false },
    ticketopen9: { type: Number, default: 0 },
    ticketchannel9: { type: String, default: '' },
    ticketmessage9: { type: String, default: '' },
    ticketreact9: { type: String, default: '671334152418623489' },
    ticketcategoryon9: { type: Boolean, default: false },
    ticketcategory9: { type: String, default: '' },
    ticketchannelname9: { type: String, default: 'Тикет' },
    ticketchannelperms9: { type: String, default: '' },
    ticketmessage1enable9: { type: Boolean, default: true },
    ticketmessage1send9: { type: String, default: '<@&721471705150914653>, пользователь создал новый тикет.' },
    ticketmessage2enable9: { type: Boolean, default: true },
    ticketmessage2send9: { type: String, default: '__**Вот твой канал, {member}**__' },
    ticketmessage3enable9: { type: Boolean, default: true },
    ticketmessage3send9: { type: String, default: 'embed' },
    ticketcloseonlyadmin9: { type: Boolean, default: true },
    ticketclosemsg9: { type: String, default: 'Для закрытия тикета, нажмите на 🔒\n**Закрыть может только администратор**' },
    ticketmsg9: { type: String, default: 'Чтобы открыть тикет, нажмите на <:emm:671334152418623489>' },



    ticketsave: { type: String, default: 'Сохранение логов...' },
    errorticketsend: { type: String, default: 'Произошла ошибка при отправке <:disagree:742945862560382987>' },
    ticketsend: { type: String, default: 'Логи отправлены <:agree:664980465740152883>' },
    ticketwaitsend: { type: String, default: 'Отправка сообщения в лс...' },
    ticketlogsaved: { type: String, default: 'Логи сохранены <:agree:664980465740152883>' },
    ticketdelete: { type: String, default: '<:errorv1:674651259424473088> Тикет будет удален через 5 секунд' },
    ticketerroreqs: { type: String, default: '<:errorv1:674651259424473088> Произошла ошибка при отправке запроса на создание логов, повторите попытку позже' },
    ticketerrorsave: { type: String, default: '<:errorv1:674651259424473088> Произошла ошибка при сохранении логов, повторите попытку позже' }
}));
